In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
df = pd.read_csv('data.csv')
df

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6814,0,0.493687,0.539468,0.543230,0.604455,0.604462,0.998992,0.797409,0.809331,0.303510,...,0.799927,0.000466,0.623620,0.604455,0.840359,0.279606,0.027064,0.566193,1,0.029890
6815,0,0.475162,0.538269,0.524172,0.598308,0.598308,0.998992,0.797414,0.809327,0.303520,...,0.799748,0.001959,0.623931,0.598306,0.840306,0.278132,0.027009,0.566018,1,0.038284
6816,0,0.472725,0.533744,0.520638,0.610444,0.610213,0.998984,0.797401,0.809317,0.303512,...,0.797778,0.002840,0.624156,0.610441,0.840138,0.275789,0.026791,0.565158,1,0.097649
6817,0,0.506264,0.559911,0.554045,0.607850,0.607850,0.999074,0.797500,0.809399,0.303498,...,0.811808,0.002837,0.623957,0.607846,0.841084,0.277547,0.026822,0.565302,1,0.044009
6818,0,0.493053,0.570105,0.549548,0.627409,0.627409,0.998080,0.801987,0.813800,0.313415,...,0.815956,0.000707,0.626680,0.627408,0.841019,0.275114,0.026793,0.565167,1,0.233902

In [3]:
train, valid, test = np.split(df.sample(frac=1), [int(0.6 * len(df)), int(0.8 * len(df))])
train

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
548,0,0.493248,0.550153,0.545747,0.607893,0.607893,0.999105,0.797435,0.809358,0.303319,...,0.806939,0.000680,0.623240,0.607892,0.840870,0.278945,0.027018,0.566049,1,0.032938
6333,0,0.430312,0.494930,0.480111,0.596888,0.596888,0.998949,0.797334,0.809267,0.303470,...,0.776323,0.000853,0.623752,0.596888,0.836963,0.290666,0.026590,0.563970,1,0.016288
6558,0,0.710915,0.748147,0.736335,0.648827,0.648827,0.999557,0.798065,0.809829,0.303474,...,0.909413,0.002479,0.624107,0.648829,0.846327,0.276052,0.026791,0.565158,1,0.080850
1606,0,0.524204,0.568088,0.566519,0.614465,0.614465,0.999103,0.797512,0.809405,0.303460,...,0.815627,0.000580,0.624030,0.614462,0.841075,0.275642,0.026853,0.565436,1,0.110958
3549,0,0.585921,0.599597,0.643022,0.621139,0.621139,0.999328,0.797822,0.809681,0.303529,...,0.835481,0.006901,0.623522,0.621140,0.842437,0.276805,0.026833,0.565350,1,0.055812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3626,0,0.528494,0.587113,0.577708,0.606610,0.606610,0.999097,0.797563,0.809454,0.303561,...,0.827556,0.007241,0.624862,0.606608,0.841875,0.276434,0.026797,0.565188,1,0.065467
5657,0,0.480330,0.548081,0.535200,0.603886,0.603864,0.998965,0.797434,0.809360,0.303611,...,0.805861,0.001573,0.623810,0.603881,0.840687,0.277470,0.026791,0.565158,1,0.044950
6764,0,0.574952,0.629634,0.616307,0.622400,0.622400,0.999254,0.797772,0.809611,0.303596,...,0.851408,0.000465,0.624083,0.622398,0.843695,0.277563,0.026806,0.565227,1,0.043830
4979,0,0.458148,0.491659,0.502757,0.600362,0.600362,0.998848,0.797209,0.809146,0.303463,...,0.768118,0.000993,0.623745,0.600359,0.837512,0.281159,0.026627,0.564230,1,0.025177
228,0,0.491639,0.542357,0.539643,0.600153,0.600153,0.999005,0.797402,0.809328,0.303471,...,0.798385,0.004416,0.629794,0.600148,0.840347,0.286181,0.028791,0.568455,1,0.018650

In [4]:
y_test = test.pop("Bankrupt?")
y_train = train.pop("Bankrupt?")
y_valid = valid.pop("Bankrupt?")
x_test = test
x_valid = valid
x_train = train

In [41]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(95),
    tf.keras.layers.Dense(428, activation='relu'),
    tf.keras.layers.Dense(524, activation='relu'),
    tf.keras.layers.Dense(1024, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
    ]
)

In [42]:
model.compile(optimizer='adam', loss='binary_crossentropy')
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
128/128 [==============================] - 4s 21ms/step - loss: 14998080.0000
Epoch 2/10
128/128 [==============================] - 3s 21ms/step - loss: 1773847.3750
Epoch 3/10
128/128 [==============================] - 3s 23ms/step - loss: 650376.3750
Epoch 4/10
128/128 [==============================] - 2s 19ms/step - loss: 216845.5625
Epoch 5/10
128/128 [==============================] - 3s 22ms/step - loss: 93433.3047
Epoch 6/10
128/128 [==============================] - 3s 20ms/step - loss: 61236.8633
Epoch 7/10
128/128 [==============================] - 2s 19ms/step - loss: 47395.5078
Epoch 8/10
128/128 [==============================] - 2s 18ms/step - loss: 8269.3350
Epoch 9/10
128/128 [==============================] - 2s 19ms/step - loss: 6432.3530
Epoch 10/10
128/128 [==============================] - 2s 18ms/step - loss: 1021.7518

In [43]:
pred = model.predict(x_valid)
pred.max

43/43 [==============================] - 0s 7ms/step

In [64]:
sit = []
for value in pred:
    if value > 0.5:
        sit.append(1)
    else:
        sit.append(0)

In [66]:
sit = np.array(sit)

In [68]:
sit.max()

1

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 95)                9120

 dense_1 (Dense)             (None, 1024)              98304

 dense_2 (Dense)             (None, 1)                 1025

=================================================================
Total params: 108,449
Trainable params: 108,449
Non-trainable params: 0
_________________________________________________________________

In [11]:
pred = model.predict(x_test)
pred

43/43 [==============================] - 0s 3ms/step

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [16]:
def MSE(y_real, y_pred):
    return (np.square(y_real - y_pred)).mean()

In [71]:
MSE(y_train, sit)

ValueError: operands could not be broadcast together with shapes (4091,) (1364,)

In [29]:
test = y_test.to_numpy
test

<bound method IndexOpsMixin.to_numpy of 5400    0
2550    0
3170    0
6270    0
4586    0
       ..
997     0
6415    0
3588    0
2852    0
1480    0
Name: Bankrupt?, Length: 1364, dtype: int64>

<bound method IndexOpsMixin.to_numpy of 5400    0
2550    0
3170    0
6270    0
4586    0
       ..
997     0
6415    0
3588    0
2852    0
1480    0
Name: Bankrupt?, Length: 1364, dtype: int64>